# Loading packages----
library(tidyverse)
library(glmmTMB)
library(gridExtra)
library(sjPlot)
library(broom.mixed)
library(bbmle)
library(ggeffects)
library(factoextra)
library(kableExtra)
library(reshape2)
library(RCurl)

# data prep for reproductive success models----
#data import and cleanup, ensuring that all columns are appropriate types
ANI <- getURL("https://raw.githubusercontent.com/QuinlanMann/Increasing_Group_size/main/NEST_SUMMARY_ANIS.csv")
ANI <- read.csv(text =ANI)
ANI<-ANI	%>% 
        mutate(NULL, 
               ADULTS=as.numeric(ADULTS), 
               EGGS_BURIED=as.numeric(EGGS_BURIED),
               EGGS_BURIED=as.numeric(EGGS_BURIED), 
               EGGS_UNBURIED=as.numeric(EGGS_UNBURIED),
               HATCHED=as.numeric(HATCHED), 
               FLEDGED=as.numeric(FLEDGED),
               TOT_EGGS=as.numeric(TOT_EGGS),
               LOCATION=as.factor(LOCATION),
               YEAR=as.factor(YEAR), 
               SITE=as.factor(SITE)	
        )
#warnings show NAs introduced by coercion
#creates proportional values for
        #eggs incubated per eggs laid
ANI$EpEg<-(ANI$EGGS_UNBURIED/ANI$TOT_EGGS)
        #eggs hatched per eggs incubated
ANI$HpEg<-(ANI$HATCHED/ANI$EGGS_UNBURIED)
        #chicks fledged per eggs hatched
ANI$FpHa<-(ANI$FLEDGED/ANI$HATCHED)

#removes the missing values
ANI<- ANI[!(is.na(ANI$ADULTS)), ] 
ANI<- ANI[! (ANI$ADULTS==1), ] #removes the record of 1 adult from the data set
ANI<-ANI %>% #removes the unknown groups
  group_by(SITE) %>%
  filter(n() > 1)

#Creates dataset of groups with nests pooled by group-year
ANI2<-ANI%>%
  group_by(YEAR, LOCATION, SITE, ADULTS)%>%
  summarize(TOT_EGGS=sum(TOT_EGGS, na.rm=T), 
            EGGS_BURIED=sum(EGGS_BURIED, na.rm=T), 
            EGGS_UNBURIED=sum(EGGS_UNBURIED, na.rm=T), 
            HATCHED=sum(HATCHED, na.rm=T), 
            FLEDGED=sum(FLEDGED, na.rm=T), 
            NESTS=length(NEST_ATTMPT))

#if the group failed to produce offspring at a previous stage, they were omitted from successive categories
ANI2<-ANI2 %>% mutate(FLEDGED = ifelse(FLEDGED == 0 & HATCHED == 0, NA, FLEDGED),
                      HATCHED = ifelse(HATCHED == 0 & EGGS_UNBURIED == 0, NA, HATCHED), 
                      EGGS_UNBURIED = ifelse(EGGS_UNBURIED == 0 & TOT_EGGS == 0, NA, EGGS_UNBURIED), 
                      TOT_EGGS = ifelse(TOT_EGGS == 0, NA, TOT_EGGS))

#creation of a "female group size" variable to be consistent with previous published work in this system
#see Schmaltz et al. 2008 for jsutification
ANI$FEM<-floor(ANI$ADULTS/2)
ANI2$FEM<-floor(ANI2$ADULTS/2)

#Creating new datasets for the proportional analyses that omit zeros, NAs, and Infinite values that would lead to errors
#proportion of eggs laid that are incuabted dataset
ANI_EpEg <- data.frame(ANI2$ADULTS, ANI2$EGGS_UNBURIED, ANI2$TOT_EGGS, ANI2$YEAR, ANI2$SITE, ANI2$LOCATION, ANI2$NESTS)
ANI_EpEg$ANI2.EpEg<-ANI_EpEg$ANI2.EGGS_UNBURIED/ANI_EpEg$ANI2.TOT_EGGS
ANI_EpEg <- ANI_EpEg[!is.na(ANI_EpEg$ANI2.EpEg), ] #removes NAs
ANI_EpEg <- ANI_EpEg[!(ANI_EpEg$ANI2.EpEg>1),] #removes the infinity values generated by dividing by zero

#proportion of eggs that hatch that are incubated dataset
ANI_HpEg <- data.frame(ANI2$ADULTS, ANI2$EGGS_UNBURIED, ANI2$HATCHED, ANI2$YEAR, ANI2$SITE, ANI2$LOCATION, ANI2$NESTS)
ANI_HpEg$ANI2.HpEg<-ANI_HpEg$ANI2.HATCHED/ANI_HpEg$ANI2.EGGS_UNBURIED
ANI_HpEg <- ANI_HpEg[!is.na(ANI_HpEg$ANI2.HpEg), ] #removes NAs
ANI_HpEg <- ANI_HpEg[!(ANI_HpEg$ANI2.HpEg>1),] #removes the infinity values generated by dividing by zero

#proportion of fledged chicks that hatch dataset
ANI_FpHa <- data.frame(ANI2$ADULTS, ANI2$HATCHED, ANI2$FLEDGED, ANI2$YEAR, ANI2$SITE, ANI2$LOCATION, ANI2$NESTS)
ANI_FpHa$ANI2.FpHa<-ANI_FpHa$ANI2.FLEDGED/ANI_FpHa$ANI2.HATCHED
ANI_FpHa <- na.omit(ANI_FpHa) #removes NAs
ANI_FpHa <- ANI_FpHa[!(ANI_FpHa$ANI2.FpHa>1),]

# Reproductive success modelling----
#models of group success
Tot.nb2.1<-glmmTMB(TOT_EGGS~FEM+NESTS+SITE+(1|SITE:LOCATION)+(1|YEAR),
                   family="nbinom2", 	
                   data = ANI2)	
Inc.nb2.1<-glmmTMB(EGGS_UNBURIED~FEM+NESTS+SITE+(1|SITE:LOCATION)+(1|YEAR),	
                   family="nbinom2", 	
                   data = ANI2)	
Hatc.p.1<- glmmTMB(HATCHED ~ FEM+NESTS+SITE+(1|SITE:LOCATION)+(1|YEAR),
                   data=ANI2, 	
                   family = poisson(link="log"))	
Fled.p.1<- glmmTMB(FLEDGED ~ FEM+NESTS+SITE+(1|SITE:LOCATION)+(1|YEAR),
                   data=ANI2, 	
                   family = poisson(link="log"))	

#models with offsets to account for per female output
Tot.nb2.2<-glmmTMB(TOT_EGGS~FEM+NESTS+SITE+offset(log(FEM))+(1|SITE:LOCATION)+(1|YEAR),	
                   family="nbinom2", 	
                   data = ANI2)	
Inc.nb2.2<-glmmTMB(EGGS_UNBURIED~FEM+NESTS+SITE+offset(log(FEM))+(1|SITE:LOCATION)+(1|YEAR),	
                   family="nbinom2", 	
                   data = ANI2)	
Hatc.p.2<- glmmTMB(HATCHED ~ FEM+NESTS+SITE+offset(log(FEM))+(1|SITE:LOCATION)+(1|YEAR),	
                   data=ANI2, 	
                   family = poisson(link="log"))	
Fled.p.2<- glmmTMB(FLEDGED ~ FEM+NESTS+SITE+offset(log(FEM))+(1|SITE:LOCATION)+(1|YEAR),	
                   data=ANI2, 	
                   family = poisson(link="log"))

## Binomial models of successes in reproduction measures
ANI_EpEg$FEM<-floor(ANI_EpEg$ANI2.ADULTS/2)
EpEg.b.1 <- glmmTMB(ANI2.EpEg ~ FEM+ANI2.NESTS+ANI2.SITE+(1|ANI2.SITE:ANI2.LOCATION)+(1|ANI2.YEAR), 
                    data=ANI_EpEg, 
                    weights = ANI2.TOT_EGGS,
                    family = binomial(link = "logit"))	

ANI_HpEg$FEM<-floor(ANI_HpEg$ANI2.ADULTS/2)
HpEg.b.1 <- glmmTMB(ANI2.HpEg~ FEM+ANI2.NESTS+ANI2.SITE+(1|ANI2.SITE:ANI2.LOCATION)+(1|ANI2.YEAR), 	
                    data=ANI_HpEg, 	
                    weights = ANI2.EGGS_UNBURIED,
                    family = binomial(link = "logit"))	

ANI_FpHa$FEM<-floor(ANI_FpHa$ANI2.ADULTS/2)
FpHa.b.1 <- glmmTMB(ANI2.FpHa ~ FEM+ANI2.NESTS+ANI2.SITE+(1|ANI2.SITE:ANI2.LOCATION)+(1|ANI2.YEAR), 
                    data=ANI_FpHa, 
                    weights=ANI2.HATCHED,
                    family = binomial(link = "logit"))

# p-value corrections----
p_values<-c(tidy(Tot.nb2.1)[[8]][2],
            tidy(Inc.nb2.1)[[8]][2],
            tidy(Hatc.p.1)[[8]][2],
            tidy(Fled.p.1)[[8]][2],
            tidy(Tot.nb2.2)[[8]][2],
            tidy(Inc.nb2.2)[[8]][2],
            tidy(Hatc.p.2)[[8]][2],
            tidy(Fled.p.2)[[8]][2],
            tidy(EpEg.b.1)[[8]][2],
            tidy(HpEg.b.1)[[8]][2],
            tidy(FpHa.b.1)[[8]][2])

p_order<-c("laid", "inc", "hatch", "fledge", 
           "laidpc", "incpc", "hatchpc", "fledgepc", 
           "princ", "prhatch", "prfledge")

p_corrected<-c(p.adjust(p_values[1:4], method = 'holm'), 
               p.adjust(p_values[5:8], method = 'holm'), 
               p.adjust(p_values[9:11], method = 'holm'))

p_holm<-cbind.data.frame(p_order, p_values, p_corrected)

# making tables to visualize the data----
kbl(
  cbind(
    (rbind(
      (tidy(Tot.nb2.1)%>%
         mutate(term=recode(term, 
                            `FEM`="Female group size",
                            `(Intercept)`="Intercept"))),
      (tidy(Inc.nb2.1)%>%
         mutate(term=recode(term, 
                            `FEM`="Female group size",
                            `(Intercept)`="Intercept"))),
      (tidy(Hatc.p.1)%>%
         mutate(term=recode(term, 
                            `FEM`="Female group size",
                            `(Intercept)`="Intercept"))),
      (tidy(Fled.p.1)%>%
         mutate(term=recode(term, 
                            `FEM`="Female group size",
                            `(Intercept)`="Intercept"))))),
    (rbind(
      (tidy(Tot.nb2.2)%>%
         mutate(term=recode(term, 
                            `FEM`="Female group size",
                            `(Intercept)`="Intercept"))),
      (tidy(Inc.nb2.2)%>%
         mutate(term=recode(term, 
                            `FEM`="Female group size",
                            `(Intercept)`="Intercept"))),
      (tidy(Hatc.p.2)%>%
         mutate(term=recode(term, 
                            `FEM`="Female group size",
                            `(Intercept)`="Intercept"))),
      (tidy(Fled.p.2)%>%
         mutate(term=recode(term, 
                            `FEM`="Female group size",
                            `(Intercept)`="Intercept")))))
  )[-c(1,2,9:12)],
  col.names = c("grp", "Term", "Estimate", "Std. Err.", "z value", "p value","Estimate", "Std. Err.", "z value", "p value"), 
  caption="summary of probability models shown in log(odds) scale",
  booktabs = T)%>%
  pack_rows(index = c("Eggs laid"= 6,
                      "incubation" = 6, 
                      "hatching" = 6, 
                      "fledging" = 6))%>%
  kable_styling(latex_options = "HOLD_position")

kbl(rbind(
  (tidy(EpEg.b.1)[-c(1:2)]%>%
     mutate(term=recode(term, 
                        `FEM`="Female group size",
                        `(Intercept)`="Intercept", 
                        `ANI2.NESTS`="Nesting attempts/group/season", 
                        `ANI2.SITELC`="Study Site"))), 
  (tidy(HpEg.b.1)[-c(1:2)]%>%
     mutate(term=recode(term, 
                        `FEM`="Female group size",
                        `(Intercept)`="Intercept", 
                        `ANI2.NESTS`="Nesting attempts/group/season", 
                        `ANI2.SITELC`="Study Site"))), 
  (tidy(FpHa.b.1)[-c(1:2)]%>%
     mutate(term=recode(term, 
                        `FEM`="Female group size",
                        `(Intercept)`="Intercept", 
                        `ANI2.NESTS`="Nesting attempts/group/season", 
                        `ANI2.SITELC`="Study Site")))), 
  col.names = c("grp", "Term", "Estimate", "Std. Err.", "z value", "p value"), 
  caption="summary of probability models shown in log(odds) scale",
  booktabs = T)%>%
  pack_rows(index = c("Pr(incubation)" = 6, 
                      "Pr(hatching)" = 6, 
                      "Pr(fledging)" = 6))%>%
  kable_styling(latex_options = "HOLD_position")

# Generating figure publications----

#Reproductive success plots
grid.arrange(
  plot(ggpredict(Tot.nb2.1, 
                 terms ="FEM"))+
    geom_jitter(data=ANI2, aes(FEM, TOT_EGGS/NESTS), 
                color="black",
                fill="black",
                stroke=0,
                width=0.075, 
                height=0.25, 
                pch=21, 
                size=3)+
    scale_y_continuous(breaks=c(0, 30, 60, 90))+
    scale_x_continuous(lim=c(1,10), breaks=c(2,4,6,8,10))+
    labs(x="Female group size", y="Eggs laid", title="a")+
    theme(
      text = element_text(family="Arial", size = 12, color="black"),
      axis.text.x = element_text(size=12, color = "black"),
      axis.text.y = element_text(size=12, color="black"),
      axis.ticks = element_line(color="black"),
      axis.line.x = element_line(color="black"),
      axis.line.y = element_line(color="black"),
      axis.title=element_text(color="black"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "white", fill=NA, size=1)), 
  plot(ggeffect(Tot.nb2.2, 
                terms ="FEM", 
                offset=0))+
    geom_jitter(data=ANI2, aes(FEM, (TOT_EGGS/FEM)/NESTS), 
                color="black",
                fill="black",
                stroke=0, 
                width=0.075, 
                height=0.25, 
                pch=21, 
                size=3)+
    scale_y_continuous(breaks=c(0, 10, 20, 30))+
    scale_x_continuous(lim=c(1,10), breaks=c(2,4,6,8,10))+
    labs(x="Female group size", y="Eggs laid per capita", title="b")+
    theme(
      text = element_text(family="Arial", size = 12, color="black"),
      axis.text.x = element_text(size=12, color = "black"),
      axis.text.y = element_text(size=12, color="black"),
      axis.ticks = element_line(color="black"),
      axis.line.x = element_line(color="black"),
      axis.title=element_text(color="black"),
      axis.line.y = element_line(color="black"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "white", fill=NA, size=1)),
  plot(ggpredict(Inc.nb2.1, 
                 terms ="FEM"))+
    geom_jitter(data=ANI2, aes(FEM, EGGS_UNBURIED/NESTS), 
                color="black",
                fill="black",
                stroke=0,
                width=0.075, 
                height=0.25, 
                pch=21, 
                size=3)+
    scale_y_continuous(breaks=c(0, 10, 20, 30))+
    scale_x_continuous(lim=c(1,10), breaks=c(2,4,6,8,10))+
    labs(x="Female group size", y="Eggs incubated", title="c")+
    theme(
      text = element_text(family="Arial", size = 12, color="black"),
      axis.text.x = element_text(size=12, color = "black"),
      axis.text.y = element_text(size=12, color="black"),
      axis.ticks = element_line(color="black"),
      axis.line.x = element_line(color="black"),
      axis.line.y = element_line(color="black"),
      panel.grid.major = element_blank(),
      axis.title=element_text(color="black"),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "white", fill=NA, size=1)),
  plot(ggeffect(Inc.nb2.2, 
                terms ="FEM", 
                offset=0))+
    geom_jitter(data=ANI2, aes(FEM, (EGGS_UNBURIED/FEM)/NESTS), 
                color="black",
                fill="black",
                stroke=0,
                width=0.075, 
                height=0.25, 
                pch=21, 
                size=3)+
    scale_y_continuous(breaks=c(0, 5, 10, 15, 20, 25))+
    scale_x_continuous(lim=c(1,10), breaks=c(2,4,6,8,10))+
    labs(x="Female group size", y="Eggs incubated per capita", title="d")+
    theme(
      text = element_text(family="Arial", size = 12, color="black"),
      axis.title=element_text(color="black"),
      axis.text.x = element_text(size=12, color = "black"),
      axis.text.y = element_text(size=12, color="black"),
      axis.ticks = element_line(color="black"),
      axis.line.x = element_line(color="black"),
      axis.line.y = element_line(color="black"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "white", fill=NA, size=1)),
  plot(ggpredict(Hatc.p.1, 
                 terms ="FEM"))+
    geom_jitter(data=ANI2, aes(FEM, HATCHED/NESTS), 
                color="black",
                fill="black",
                stroke=0,
                width=0.075, 
                height=0.25, 
                pch=21, 
                size=3)+
    scale_y_continuous(breaks=c(0, 3, 6, 9, 12))+
    scale_x_continuous(lim=c(1,10), breaks=c(2,4,6,8,10))+
    labs(x="Female group size", y="Eggs hatched", title="e")+
    theme(
      text = element_text(family="Arial", size = 12, color="black"),
      axis.title=element_text(color="black"),
      axis.text.x = element_text(size=12, color = "black"),
      axis.text.y = element_text(size=12, color="black"),
      axis.ticks = element_line(color="black"),
      axis.line.x = element_line(color="black"),
      axis.line.y = element_line(color="black"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "white", fill=NA, size=1)),
  plot(ggeffect(Hatc.p.2, 
                terms ="FEM", 
                offset=0))+
    geom_jitter(data=ANI2, aes(FEM, (HATCHED/FEM)/NESTS), 
                color="black",
                fill="black",
                stroke=0,
                width=0.075, 
                height=0.25, 
                pch=21, 
                size=3)+
    scale_y_continuous(breaks=c(0, 2, 4, 6, 8, 10))+
    scale_x_continuous(lim=c(1,10), breaks=c(2,4,6,8,10))+
    labs(x="Female group size", y="Eggs hatched per capita", title="f")+
    theme(
      axis.title=element_text(color="black"),
      text = element_text(family="Arial", size = 12, color="black"),
      axis.text.x = element_text(size=12, color = "black"),
      axis.text.y = element_text(size=12, color="black"),
      axis.ticks = element_line(color="black"),
      axis.line.x = element_line(color="black"),
      axis.line.y = element_line(color="black"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "white", fill=NA, size=1)),
  plot(ggpredict(Fled.p.1, 
                 terms ="FEM"))+
    geom_jitter(data=ANI2, aes(FEM, FLEDGED/NESTS), 
                color="black",
                fill="black",
                stroke=0,
                width=0.075, 
                height=0.25, 
                pch=21, 
                size=3)+
    scale_y_continuous(breaks = c(0,2,4,6,8,10))+
    scale_x_continuous(lim=c(1,10), breaks=c(2,4,6,8,10))+
    labs(x="Female group size", y="Chicks fledged", title="g")+
    theme(
      text = element_text(family="Arial", size = 12, color="black"),
      axis.text.x = element_text(size=12, color = "black"),
      axis.text.y = element_text(size=12, color="black"),
      axis.ticks = element_line(color="black"),
      axis.line.x = element_line(color="black"),
      axis.line.y = element_line(color="black"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.title=element_text(color="black"),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "white", fill=NA, size=1)),
  plot(ggeffect(Fled.p.2, 
                terms ="FEM", 
                offset=0))+
    geom_jitter(data=ANI2, aes(FEM, (FLEDGED/FEM)/NESTS), 
                color="black",
                fill="black",
                stroke=0,
                width=0.075, 
                height=0.25, 
                pch=21, 
                size=3)+
    scale_y_continuous(breaks = c(0,2,4,6,8,10))+
    scale_x_continuous(lim=c(1,10), breaks=c(2,4,6,8,10))+
    labs(x="Female group size", y="Chicks fledged per capita", title="h")+
    theme(
      text = element_text(family="Arial", size = 12, color="black"),
      axis.text.x = element_text(size=12, color = "black"),
      axis.text.y = element_text(size=12, color="black"),
      axis.title=element_text(color="black"),
      axis.ticks = element_line(color="black"),
      axis.line.x = element_line(color="black"),
      axis.line.y = element_line(color="black"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "white", fill=NA, size=1)),
  ncol=2)

#Probability model plots
grid.arrange(
  plot(ggpredict(EpEg.b.1, 
                 terms ="FEM"))+
    geom_jitter(data=ANI_EpEg, aes(FEM, ANI2.EpEg), 
                color="black",
                fill="black",
                stroke=0,
                width=0.075,
                pch=21, 
                size=3)+
    scale_y_continuous(labels = scales::percent, lim=c(0,1))+
    scale_x_continuous(lim=c(1,10), breaks=c(2,4,6,8,10))+
    labs(x="Female group size", y="Probability of being incubated", title="a")+
    theme(
      text = element_text(family="Arial", size = 12, color="black"),
      axis.text.x = element_text(size=12, color = "black"),
      axis.title=element_text(color="black"),
      axis.text.y = element_text(size=12, color="black"),
      axis.ticks = element_line(color="black"),
      axis.line.x = element_line(color="black"),
      axis.line.y = element_line(color="black"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "white", fill=NA, size=1)),
  plot(ggpredict(HpEg.b.1, 
                 terms ="FEM"))+
    geom_jitter(data=ANI_HpEg, aes(FEM, ANI2.HpEg), 
                color="black",
                fill="black",
                stroke=0,
                width=0.075,
                pch=21, 
                size=3)+
    scale_y_continuous(labels = scales::percent, lim=c(0,1))+
    scale_x_continuous(lim=c(1,10), breaks=c(2,4,6,8,10))+
    labs(x="Female group size", y="Probability of hatching", title="b")+
    theme(
      text = element_text(family="Arial", size = 12, color="black"),
      axis.text.x = element_text(size=12, color = "black"),
      axis.text.y = element_text(size=12, color="black"),
      axis.ticks = element_line(color="black"),
      axis.title=element_text(color="black"),
      axis.line.x = element_line(color="black"),
      axis.line.y = element_line(color="black"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "white", fill=NA, size=1)),
  plot(ggpredict(FpHa.b.1, 
                 terms ="FEM"))+
    geom_jitter(data=ANI_FpHa, aes(FEM, ANI2.FpHa), 
                color="black",
                fill="black",
                stroke=0,
                width=0.075, 
                pch=21, 
                size=3)+
    scale_y_continuous(labels = scales::percent, lim=c(0,1))+
    scale_x_continuous(lim=c(1,10), breaks=c(2,4,6,8,10))+
    labs(x="Female group size", y="Probability of fledging", title="c")+
    theme(
      text = element_text(family="Arial", size = 12, color="black"),
      axis.text.x = element_text(size=12, color = "black"),
      axis.text.y = element_text(size=12, color="black"),
      axis.ticks = element_line(color="black"),
      axis.line.x = element_line(color="black"),
      axis.line.y = element_line(color="black"),
      panel.grid.major = element_blank(),
      axis.title=element_text(color="black"),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(colour = "white", fill=NA, size=1)),
  ncol=1)

# supplemental Analyses----
#creation of "Just first nest" dataset
ANI3<- ANI
ANI3<- ANI[(ANI$NEST_ATTMPT<2), ] 
ANI3$NEST_ATTMPT<-replace(ANI3$NEST_ATTMPT, is.na(ANI3$NEST_ATTMPT), 1) 
ANI3<-ANI3[!is.na(ANI3$FEM),]

#creation of "Just first successful nest: datasest
ANI$SURV <- ifelse(is.na(ANI$FLEDGED) | ANI$FLEDGED==0, "FAIL", "SUCC")

ANI4<-subset(ANI, SURV=="SUCC")%>%
  group_by(YEAR, 
           LOCATION)%>%
  arrange(NEST_ATTMPT, 
          .by_group=T)%>% 
  filter(row_number(NEST_ATTMPT) == 1)

#for probabaility models
ANI3_EpEg <- data.frame(ANI3$ADULTS, ANI3$EGGS_UNBURIED, ANI3$TOT_EGGS, ANI3$YEAR, ANI3$SITE, ANI3$LOCATION)
ANI3_EpEg$ANI3.EpEg<-ANI3_EpEg$ANI3.EGGS_UNBURIED/ANI3_EpEg$ANI3.TOT_EGGS
ANI3_EpEg <- ANI3_EpEg[!is.na(ANI3_EpEg$ANI3.EpEg), ] #removes NAs
ANI3_EpEg <- ANI3_EpEg[!(ANI3_EpEg$ANI3.EpEg>1),] #removes the infinity values generated by dividing by zero

ANI3_HpEg <- data.frame(ANI3$ADULTS, ANI3$EGGS_UNBURIED, ANI3$HATCHED, ANI3$YEAR, ANI3$SITE, ANI3$LOCATION)
ANI3_HpEg$ANI3.HpEg<-ANI3_HpEg$ANI3.HATCHED/ANI3_HpEg$ANI3.EGGS_UNBURIED
ANI3_HpEg <- ANI3_HpEg[!is.na(ANI3_HpEg$ANI3.HpEg), ] #removes NAs
ANI3_HpEg <- ANI3_HpEg[!(ANI3_HpEg$ANI3.HpEg>1),] #removes the infinity values generated by dividing by zero

ANI3_FpHa <- data.frame(ANI3$ADULTS, ANI3$HATCHED, ANI3$FLEDGED, ANI3$YEAR, ANI3$SITE, ANI3$LOCATION)
ANI3_FpHa$ANI3.FpHa<-ANI3_FpHa$ANI3.FLEDGED/ANI3_FpHa$ANI3.HATCHED
ANI3_FpHa <- na.omit(ANI3_FpHa) #removes NAs
ANI3_FpHa <- ANI3_FpHa[!(ANI3_FpHa$ANI3.FpHa>1),]

ANI4_EpEg <- data.frame(ANI4$ADULTS, ANI4$EGGS_UNBURIED, ANI4$TOT_EGGS, ANI4$YEAR, ANI4$SITE, ANI4$LOCATION)
ANI4_EpEg$ANI4.EpEg<-ANI4_EpEg$ANI4.EGGS_UNBURIED/ANI4_EpEg$ANI4.TOT_EGGS
ANI4_EpEg <- ANI4_EpEg[!is.na(ANI4_EpEg$ANI4.EpEg), ] #removes NAs
ANI4_EpEg <- ANI4_EpEg[!(ANI4_EpEg$ANI4.EpEg>1),] #removes the infinity values generated by dividing by zero

ANI4_HpEg <- data.frame(ANI4$ADULTS, ANI4$EGGS_UNBURIED, ANI4$HATCHED, ANI4$YEAR, ANI4$SITE, ANI4$LOCATION)
ANI4_HpEg$ANI4.HpEg<-ANI4_HpEg$ANI4.HATCHED/ANI4_HpEg$ANI4.EGGS_UNBURIED
ANI4_HpEg <- ANI4_HpEg[!is.na(ANI4_HpEg$ANI4.HpEg), ] #removes NAs
ANI4_HpEg <- ANI4_HpEg[!(ANI4_HpEg$ANI4.HpEg>1),] #removes the infinity values generated by dividing by zero

ANI4_FpHa <- data.frame(ANI4$ADULTS, ANI4$HATCHED, ANI4$FLEDGED, ANI4$YEAR, ANI4$SITE, ANI4$LOCATION)
ANI4_FpHa$ANI4.FpHa<-ANI4_FpHa$ANI4.FLEDGED/ANI4_FpHa$ANI4.HATCHED
ANI4_FpHa <- na.omit(ANI4_FpHa) #removes NAs
ANI4_FpHa <- ANI4_FpHa[!(ANI4_FpHa$ANI4.FpHa>1),]

#supplemental models
#models of group success
Tot.nb2.1_ANI3<-glmmTMB(TOT_EGGS~FEM+SITE+(1|SITE:LOCATION)+(1|YEAR),
                        family="nbinom2", 	
                        data = ANI3)	
Inc.nb2.1_ANI3<-glmmTMB(EGGS_UNBURIED~FEM+SITE+(1|SITE:LOCATION)+(1|YEAR),	
                        family="nbinom2", 	
                        data = ANI3)	
Hatc.p.1_ANI3<- glmmTMB(HATCHED ~ FEM+SITE+(1|SITE:LOCATION)+(1|YEAR),
                        data=ANI3, 	
                        family = poisson(link="log"))	
Fled.p.1_ANI3<- glmmTMB(FLEDGED ~ FEM+SITE+(1|SITE:LOCATION)+(1|YEAR),
                        data=ANI3, 	
                        family = poisson(link="log"))	
Tot.nb2.1_ANI4<-glmmTMB(TOT_EGGS~FEM+SITE+(1|SITE:LOCATION)+(1|YEAR),
                        family="nbinom2", 	
                        data = ANI4)	
Inc.nb2.1_ANI4<-glmmTMB(EGGS_UNBURIED~FEM+SITE+(1|SITE:LOCATION)+(1|YEAR),	
                        family="nbinom2", 	
                        data = ANI4)	
Hatc.p.1_ANI4<- glmmTMB(HATCHED ~ FEM+SITE+(1|SITE:LOCATION)+(1|YEAR),
                        data=ANI4, 	
                        family = poisson(link="log"))	
Fled.p.1_ANI4<- glmmTMB(FLEDGED ~ FEM+SITE+(1|SITE:LOCATION)+(1|YEAR),
                        data=ANI4, 	
                        family = poisson(link="log"))	

#models with offsets to account for per female output
Tot.nb2.2_ANI3<-glmmTMB(TOT_EGGS~FEM+SITE+offset(log(FEM))+(1|SITE:LOCATION)+(1|YEAR),	
                        family="nbinom2", 	
                        data = ANI3)	
Inc.nb2.2_ANI3<-glmmTMB(EGGS_UNBURIED~FEM+SITE+offset(log(FEM))+(1|SITE:LOCATION)+(1|YEAR),	
                        family="nbinom2", 	
                        data = ANI3)	
Hatc.p.2_ANI3<- glmmTMB(HATCHED ~ FEM+SITE+offset(log(FEM))+(1|SITE:LOCATION)+(1|YEAR),	
                        data=ANI3, 	
                        family = poisson(link="log"))	
Fled.p.2_ANI3<- glmmTMB(FLEDGED ~ FEM+SITE+offset(log(FEM))+(1|SITE:LOCATION)+(1|YEAR),	
                        data=ANI3, 	
                        family = poisson(link="log"))
Tot.nb2.2_ANI4<-glmmTMB(TOT_EGGS~FEM+SITE+offset(log(FEM))+(1|SITE:LOCATION)+(1|YEAR),	
                        family="nbinom2", 	
                        data = ANI4)	
Inc.nb2.2_ANI4<-glmmTMB(EGGS_UNBURIED~FEM+SITE+offset(log(FEM))+(1|SITE:LOCATION)+(1|YEAR),	
                        family="nbinom2", 	
                        data = ANI4)	
Hatc.p.2_ANI4<- glmmTMB(HATCHED ~ FEM+SITE+offset(log(FEM))+(1|SITE:LOCATION)+(1|YEAR),	
                        data=ANI4, 	
                        family = poisson(link="log"))	
Fled.p.2_ANI4<- glmmTMB(FLEDGED ~ FEM+SITE+offset(log(FEM))+(1|SITE:LOCATION)+(1|YEAR),	
                        data=ANI4, 	
                        family = poisson(link="log"))

#probabaility models
ANI3_EpEg$FEM<-floor(ANI3_EpEg$ANI3.ADULTS/2)
EpEg.b.1_ANI3 <- glmmTMB(ANI3.EpEg ~ FEM+ANI3.SITE+(1|ANI3.SITE:ANI3.LOCATION)+(1|ANI3.YEAR), 
                         data=ANI3_EpEg, 
                         weights = ANI3.TOT_EGGS,
                         family = binomial(link = "logit"))	
ANI3_HpEg$FEM<-floor(ANI3_HpEg$ANI3.ADULTS/2)
HpEg.b.1_ANI3 <- glmmTMB(ANI3.HpEg~ FEM+ANI3.SITE+(1|ANI3.SITE:ANI3.LOCATION)+(1|ANI3.YEAR), 	
                         data=ANI3_HpEg, 	
                         weights = ANI3.EGGS_UNBURIED,
                         family = binomial(link = "logit"))	
ANI3_FpHa$FEM<-floor(ANI3_FpHa$ANI3.ADULTS/2)
FpHa.b.1_ANI3 <- glmmTMB(ANI3.FpHa ~ FEM+ANI3.SITE+(1|ANI3.SITE:ANI3.LOCATION)+(1|ANI3.YEAR), 
                         data=ANI3_FpHa, 
                         weights=ANI3.HATCHED,
                         family = binomial(link = "logit"))
ANI4_EpEg$FEM<-floor(ANI4_EpEg$ANI4.ADULTS/2)
EpEg.b.1_ANI4 <- glmmTMB(ANI4.EpEg ~ FEM+ANI4.SITE+(1|ANI4.SITE:ANI4.LOCATION)+(1|ANI4.YEAR), 
                         data=ANI4_EpEg, 
                         weights = ANI4.TOT_EGGS,
                         family = binomial(link = "logit"))	
ANI4_HpEg$FEM<-floor(ANI4_HpEg$ANI4.ADULTS/2)
HpEg.b.1_ANI4 <- glmmTMB(ANI4.HpEg~ FEM+ANI4.SITE+(1|ANI4.SITE:ANI4.LOCATION)+(1|ANI4.YEAR), 	
                         data=ANI4_HpEg, 	
                         weights = ANI4.EGGS_UNBURIED,
                         family = binomial(link = "logit"))	
ANI4_FpHa$FEM<-floor(ANI4_FpHa$ANI4.ADULTS/2)
FpHa.b.1_ANI4 <- glmmTMB(ANI4.FpHa ~ FEM+ANI4.SITE+(1|ANI4.SITE:ANI4.LOCATION)+(1|ANI4.YEAR), 
                         data=ANI4_FpHa, 
                         weights=ANI4.HATCHED,
                         family = binomial(link = "logit"))

#outputting supplemental tables
df1<-as.data.frame(cbind(
  (rbind(
    c(NA, NA, "Eggs Laid", NA, NA, NA, NA, NA),
    (tidy(Tot.nb2.1_ANI3)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Eggs Incubated", NA, NA, NA, NA, NA),
    (tidy(Inc.nb2.1_ANI3)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Eggs Hatched", NA, NA, NA, NA, NA),
    (tidy(Hatc.p.1_ANI3)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Chicks Fledged", NA, NA, NA, NA, NA),
    (tidy(Fled.p.1_ANI3)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))))),
  (rbind(
    c(NA, NA, "Eggs Laid per capita", NA, NA, NA, NA, NA),
    (tidy(Tot.nb2.2_ANI3)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Eggs Incubated per capita", NA, NA, NA, NA, NA),
    (tidy(Inc.nb2.2_ANI3)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Eggs Hatched per capita", NA, NA, NA, NA, NA),
    (tidy(Hatc.p.2_ANI3)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Chicks Fledged per capita", NA, NA, NA, NA, NA),
    (tidy(Fled.p.2_ANI3)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))))))[-c(1,2,9:12)])

df2<-as.data.frame(rbind(
  c("Proportion incubated", NA, NA, NA, NA, NA),
  (tidy(EpEg.b.1_ANI3)[-c(1:2)]%>%
     mutate(term=recode(term, 
                        `FEM`="Female group size",
                        `(Intercept)`="Intercept", 
                        `ANI3.SITELC`="Study Site"))), 
  c("Proportion hatched", NA, NA, NA, NA, NA),
  (tidy(HpEg.b.1_ANI3)[-c(1:2)]%>%
     mutate(term=recode(term, 
                        `FEM`="Female group size",
                        `(Intercept)`="Intercept", 
                        `ANI3.SITELC`="Study Site"))), 
  c("Proportion fledged", NA, NA, NA, NA, NA),
  (tidy(FpHa.b.1_ANI3)[-c(1:2)]%>%
     mutate(term=recode(term, 
                        `FEM`="Female group size",
                        `(Intercept)`="Intercept", 
                        `ANI3.SITELC`="Study Site")))))

df3<-as.data.frame(cbind(
  (rbind(
    c(NA, NA, "Eggs Laid", NA, NA, NA, NA, NA),
    (tidy(Tot.nb2.1_ANI4)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Eggs Incubated", NA, NA, NA, NA, NA),
    (tidy(Inc.nb2.1_ANI4)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Eggs Hatched", NA, NA, NA, NA, NA),
    (tidy(Hatc.p.1_ANI4)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Chicks Fledged", NA, NA, NA, NA, NA),
    (tidy(Fled.p.1_ANI4)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))))),
  (rbind(
    c(NA, NA, "Eggs Laid per capita", NA, NA, NA, NA, NA),
    (tidy(Tot.nb2.2_ANI4)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Eggs Incubated per capita", NA, NA, NA, NA, NA),
    (tidy(Inc.nb2.2_ANI4)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Eggs Hatched per capita", NA, NA, NA, NA, NA),
    (tidy(Hatc.p.2_ANI4)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Chicks Fledged per capita", NA, NA, NA, NA, NA),
    (tidy(Fled.p.2_ANI4)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))))))[-c(1,2,9:12)])

df4<-as.data.frame(rbind(
  c("Proportion incubated", NA, NA, NA, NA, NA),
  (tidy(EpEg.b.1_ANI4)[-c(1:2)]%>%
     mutate(term=recode(term, 
                        `FEM`="Female group size",
                        `(Intercept)`="Intercept", 
                        `ANI4.SITELC`="Study Site"))), 
  c("Proportion hatched", NA, NA, NA, NA, NA),
  (tidy(HpEg.b.1_ANI4)[-c(1:2)]%>%
     mutate(term=recode(term, 
                        `FEM`="Female group size",
                        `(Intercept)`="Intercept", 
                        `ANI4.SITELC`="Study Site"))), 
  c("Proportion fledged", NA, NA, NA, NA, NA),
  (tidy(FpHa.b.1_ANI4)[-c(1:2)]%>%
     mutate(term=recode(term, 
                        `FEM`="Female group size",
                        `(Intercept)`="Intercept", 
                        `ANI4.SITELC`="Study Site")))))

df5<-as.data.frame(cbind(
  (rbind(
    c(NA, NA, "Eggs Laid", NA, NA, NA, NA, NA),
    (tidy(Tot.nb2.1q)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Eggs Incubated", NA, NA, NA, NA, NA),
    (tidy(Inc.nb2.1q)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Eggs Hatched", NA, NA, NA, NA, NA),
    (tidy(Hatc.p.1q)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Chicks Fledged", NA, NA, NA, NA, NA),
    (tidy(Fled.p.1q)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))))),
  (rbind(
    c(NA, NA, "Eggs Laid per capita", NA, NA, NA, NA, NA),
    (tidy(Tot.nb2.2q)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Eggs Incubated per capita", NA, NA, NA, NA, NA),
    (tidy(Inc.nb2.2q)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Eggs Hatched per capita", NA, NA, NA, NA, NA),
    (tidy(Hatc.p.2q)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))),
    c(NA, NA, "Chicks Fledged per capita", NA, NA, NA, NA, NA),
    (tidy(Fled.p.2q)%>%
       mutate(term=recode(term, 
                          `FEM`="Female group size",
                          `(Intercept)`="Intercept"))))))[-c(1,2,9:12)])

#summary stats of various datsets
sumstats<-cbind(
  rbind(
    c(NA, NA, NA, NA, NA, NA, NA),
    summary(ANI$TOT_EGGS), 
    summary(ANI$EGGS_UNBURIED), 
    summary(ANI$HATCHED), 
    summary(ANI$FLEDGED), 
    c(NA, NA, NA, NA, NA, NA, NA),
    summary(ANI2$TOT_EGGS),
    summary(ANI2$EGGS_UNBURIED),
    summary(ANI2$HATCHED),
    summary(ANI2$FLEDGED),
    c(NA, NA, NA, NA, NA, NA, NA),
    summary(ANI3$TOT_EGGS),
    summary(ANI3$EGGS_UNBURIED),
    summary(ANI3$HATCHED),
    summary(ANI3$FLEDGED),  
    c(NA, NA, NA, NA, NA, NA, NA),
    summary(ANI4$TOT_EGGS),
    summary(ANI4$EGGS_UNBURIED),
    summary(ANI4$HATCHED),
    summary(ANI4$FLEDGED))[,-c(7)],
  rbind(
    c(NA),
    sum(!is.na(ANI$TOT_EGGS)), 
    sum(!is.na(ANI$EGGS_UNBURIED)), 
    sum(!is.na(ANI$HATCHED)), 
    sum(!is.na(ANI$FLEDGED)), 
    c(NA),
    sum(!is.na(ANI2$TOT_EGGS)), 
    sum(!is.na(ANI2$EGGS_UNBURIED)), 
    sum(!is.na(ANI2$HATCHED)), 
    sum(!is.na(ANI2$FLEDGED)), 
    c(NA),
    sum(!is.na(ANI3$TOT_EGGS)), 
    sum(!is.na(ANI3$EGGS_UNBURIED)), 
    sum(!is.na(ANI3$HATCHED)), 
    sum(!is.na(ANI3$FLEDGED)), 
    c(NA),
    sum(!is.na(ANI4$TOT_EGGS)), 
    sum(!is.na(ANI4$EGGS_UNBURIED)), 
    sum(!is.na(ANI4$HATCHED)), 
    sum(!is.na(ANI4$FLEDGED)))
)
  
rownames(sumstats)<-c("Unpooled dataset", "Eggs Laid", "Eggs Incubated", "Eggs Hatched", "Chicks Fledged", 
                      "Pooled by group-year", "Eggs Laid", "Eggs Incubated", "Eggs Hatched", "Chicks Fledged", 
                      "First known breeding attempt", "Eggs Laid", "Eggs Incubated", "Eggs Hatched", "Chicks Fledged", 
                      "First known successful breeding attempt", "Eggs Laid", "Eggs Incubated", "Eggs Hatched", "Chicks Fledged")
library(tibble)
sumstats<-as.data.frame(sumstats)
colnames(sumstats) <- c("Min", "1st Quartile", "Median", "Mean", "3rd Quartile", "Max", "N")
sumstats <- rownames_to_column(sumstats, "VALUE")

#group survival
FISHER1<-as.data.frame(cbind(ANI$FEM, ANI$SURV))
FISHER1<-rename(FISHER1, 
                FEM = V1, 
                SURV = V2)
test1<-fisher.test(table(FISHER1$SURV, FISHER1$FEM), simulate.p.value = T)

SURVIVAL<-rbind(FISHER1,
               c(NA, NA),
               c("Fisher test results", NA), 
               c(test1$method, NA), 
               c("p-value=", test1$p.value))
SURVIVAL<-as.data.frame(SURVIVAL)

#renesting
FISHER2<-as.data.frame(cbind(ANI2$FEM, ANI2$NESTS))
FISHER2<-rename(FISHER2, 
               FEM = V1, 
               NESTS = V2)
test2<-fisher.test(table(FISHER2$NESTS, FISHER2$FEM), simulate.p.value = T)

NESTING<-rbind(FISHER2,
               c(NA, NA),
               c("Fisher test results", NA), 
               c(test2$method, NA), 
               c("p-value=", test2$p.value))
NESTING<-as.data.frame(NESTING)

#collecting into one dataframe
data_frames <- list("S1 Summary statistics of different datasets" = sumstats, 
                    "S2 First nest only data, count models" = df1, 
                    "S3 First nest only data, probability models" = df2,
                    "S4 First successful nest only data, count models" = df3,
                    "S5 First successful nest only data, probability models" = df4,
                    "S12 Nest count and group size" = NESTING,
                    "S13 Survival of nest and group size" = SURVIVAL
                    )

library(writexl)

#writing to my local
write_xlsx(data_frames, "C:/Users/quinl/Desktop/ANI/Supplemental.xlsx")

# supplemental figures----
library(ggstatsplot)
FISHER1$FEM <- factor(FISHER1$FEM, levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"))

ggbarstats(
  FISHER1, SURV, FEM,
  results.subtitle = F,
  subtitle = paste0(
    "Fisher's exact test", "\np-value = ",
    ifelse(test1$p.value < 0.001, "< 0.001", round(test1$p.value, 3))))

ggbarstats(
  FISHER2, NESTS, FEM,
  results.subtitle = F,
  subtitle = paste0(
    "Fisher's exact test", "\np-value = ",
    ifelse(test2$p.value < 0.001, "< 0.001", round(test2$p.value, 3))))
